# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - deploy/master/frontend
        - deploy/develop/frontend
        - deploy/master/backend
        - deploy/develop/backend
    docker:
      - image: creaticoding/alpine:1.0.0
    steps:
      - run: echo ${CIRCLE_BRANCH}
      - run:
          command: |
            echo "1";
            if [ "$CIRCLE_BRANCH" = "deploy/master/frontend" ]; then
              echo "2";
              ssh ubuntu@$SERVER_HOSTNAME -i ~/.ssh/id_creco2019 -o StrictHostKeyChecking=no <<'ENDSSH'
                sudo pgrep -f nuxt | xargs kill -9
                sudo rm -rf master_frontend
                mkdir master_frontend
                cd master_frontend
                git clone --branch deploy/master/frontend https://github.com/CreatiCoding/creati-code-box
                cd creati-code-box
                nohup ./deploy.sh </dev/null >/dev/null 2>&1 &
              ENDSSH;
              exit 0;
            elif [ "$CIRCLE_BRANCH" = "deploy/develop/frontend" ]; then
              echo "3";
              ssh ubuntu@$SERVER_HOSTNAME -i ~/.ssh/id_creco2019 -o StrictHostKeyChecking=no <<'ENDSSH'
                sudo pgrep -f nuxt | xargs kill -9
                sudo rm -rf develop_frontend
                mkdir develop_frontend
                cd develop_frontend
                git clone --branch deploy/develop/frontend https://github.com/CreatiCoding/creati-code-box
                cd creati-code-box
                nohup ./deploy.sh </dev/null >/dev/null 2>&1 &
              ENDSSH;
              exit 0;
            else
              echo "4";
              echo "other branch or error occur";
              exit 0;
            fi
workflows:
  version: 2
  asdasdsda:
    jobs:
      - build
