# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - deploy/master/frontend
        - deploy/develop/frontend
        - deploy/master/backend
        - deploy/develop/backend
    docker:
      - image: creaticoding/alpine:1.0.0
    steps:
      - checkout
      - run:
          command: |
            ./deploy.circleci.sh
