# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - deploy/master/frontend
        - deploy/develop/frontend
        - deploy/master/backend
        - deploy/develop/backend
    docker:
      - image: creaticoding/alpine:1.0.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'be:45:07:d4:ae:48:21:d9:ca:5d:ef:c2:41:03:ba:d9'
      - checkout
      - run:
          command: |
            # nohup ./deploy/deploy.circleci.sh </dev/null >/dev/null 2>&1 &
            # ./
            ssh ubuntu@$SERVER_HOSTNAME -i ~/.ssh/$SSH_FILE -o StrictHostKeyChecking=no < ./deploy/develop.frontend.sh 2>&1
