# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  depoly_master_frontend:
    branches:
      only:
        - deploy/master/frontend
    docker:
      - image: creaticoding/alpine:1.0.0
    steps:
      - run:
          command: |
            ssh ubuntu@$SERVER_HOSTNAME -i ~/.ssh/id_creco2019 -o StrictHostKeyChecking=no <<'ENDSSH'
              sudo pgrep -f nuxt | xargs kill -9
              sudo rm -rf master_frontend
              mkdir master_frontend
              cd master_frontend
              git clone --branch deploy/master/frontend https://github.com/CreatiCoding/creati-code-box
              cd creati-code-box
              nohup ./deploy.sh </dev/null >/dev/null 2>&1 &
            ENDSSH

  depoly_develop_frontend:
    branches:
      only:
        - deploy/develop/frontend
    docker:
      - image: creaticoding/alpine:1.0.0
    steps:
      - run:
          command: |
            ssh ubuntu@$SERVER_HOSTNAME -i ~/.ssh/id_creco2019 -o StrictHostKeyChecking=no <<'ENDSSH'
              sudo pgrep -f nuxt | xargs kill -9
              sudo rm -rf develop_frontend
              mkdir develop_frontend
              cd develop_frontend
              git clone --branch deploy/develop/frontend https://github.com/CreatiCoding/creati-code-box
              cd creati-code-box
              nohup ./deploy.sh </dev/null >/dev/null 2>&1 &
            ENDSSH
